common/urls.py
from __future__ import absolute_import

from django.conf.urls import url, include
from common.views import (Commands,
                          CommandExecuteList, CommandExecuteDetailApi,
                          CredentialCreate, CredentialList, CredentialDetailApi,
                          ServerCreate, ServerlList, GroupList, GroupCreate,
                          LogList, CommandLogList, WebterminalHelperDetectApi, WebterminalHelperDetectCallbackApi)
from common.api import ServerGroupViewSet, ServerInforViewSet, CommandsSequenceViewSet, CredentialViewSet
from rest_framework import routers
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

#from common.admin import OTPAdminSite
#admin.site.__class__ = OTPAdminSite

# Register webterminal api
router = routers.DefaultRouter()
router.register('servergroup', ServerGroupViewSet)
router.register('serverinfo', ServerInforViewSet)
router.register('commandssequence', CommandsSequenceViewSet)
router.register('credential', CredentialViewSet)

urlpatterns = [
    url(r'^commands/add/$', Commands.as_view(), name='commandscreate'),
    url(r'^commandslist/$', CommandExecuteList.as_view(), name='commandslist'),
    url(r'^commandsapi/$', CommandExecuteDetailApi.as_view(), name='commandsapi'),
    url(r'^credentialcreate/$', CredentialCreate.as_view(),
        name='credentialcreate'),
    url(r'^credentiallist/$', CredentialList.as_view(), name='credentiallist'),
    url(r'^credentialdetailapi/$', CredentialDetailApi.as_view(),
        name='credentialdetailapi'),
    url(r'^servercreate/$', ServerCreate.as_view(), name='servercreate'),
    url(r'^serverlist/$', ServerlList.as_view(), name='serverlist'),
    url(r'^groupcreate/$', GroupCreate.as_view(), name='groupcreate'),
    url(r'^grouplist/$', GroupList.as_view(), name='grouplist'),
    url(r'^logslist/$', LogList.as_view(), name='logslist'),
    url(r'^commandsloglist/$', CommandLogList.as_view(), name='commandsloglist'),
    url(r'^api/', include(router.urls)),
    url(r'^webterminalhelperdetect/$', WebterminalHelperDetectApi.as_view(),
        name='webterminalhelperdetectapi'),
    url(r'^webterminalhelperdetectcallback/$', csrf_exempt(WebterminalHelperDetectCallbackApi.as_view()),
        name='webterminalhelperdetectcallbackapi'),
]

permission/urls.py
from django.conf.urls import url

from permission.views import UserRegister, UserUpdate, UserList, UserDelete, PermissionCreate, PermissionList, PermissionUpdate, PermissionDelete

urlpatterns = [
    url(r'^user/add/$', UserRegister.as_view(), name='usercreate'),
    url(r'^user/(?P<pk>[0-9]+)/update/$',
        UserUpdate.as_view(), name='userupdate'),
    url(r'^user/(?P<pk>[0-9]+)/delete/$',
        UserDelete.as_view(), name='userdelete'),
    url(r'^user/$', UserList.as_view(), name='userlist'),
    url(r'^permission/$', PermissionList.as_view(), name='permissionlist'),
    url(r'^permission/add/$', PermissionCreate.as_view(), name='permissioncreate'),
    url(r'^permission/(?P<pk>[0-9]+)/update/$',
        PermissionUpdate.as_view(), name='permissionupdate'),
    url(r'^permission/(?P<pk>[0-9]+)/delete/$',
        PermissionDelete.as_view(), name='permissiondelete'),
]

webterminal/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib import admin
from webterminal.views import Index, SshLogPlay, SshTerminalKill, SshTerminalMonitor, CommandExecute, BatchCommandExecute, SshConnect, DynamicPassword
from django.contrib.auth.views import LoginView, LogoutView
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guacamole/', include('guacamole.urls')),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^sshconnect/(?P<ip>(?:(?:0|1[\d]{0,2}|2(?:[0-4]\d?|5[0-5]?|[6-9])?|[3-9]\d?)\.){3}(?:0|1[\d]{0,2}|2(?:[0-4]\d?|5[0-5]?|[6-9])?|[3-9]\d?))/(?P<serverid>[0-9]+)/$',
        SshConnect.as_view(), name='sshconnect'),
    url(r'^commandexecute/$', CommandExecute.as_view(), name='commandexecute'),
    url(r'^batchcommandexecute/$', BatchCommandExecute.as_view(),
        name='batchcommandexecute'),
    url(r'^sshterminalkill/$', SshTerminalKill.as_view(), name='sshterminalkill'),
    url(r'^sshlogplay/(?P<pk>[0-9]+)/',
        SshLogPlay.as_view(), name='sshlogplay'),
    url(r'^sshterminalmonitor/(?P<pk>[0-9]+)/',
        SshTerminalMonitor.as_view(), name='sshterminalmonitor'),
    url(r'^accounts/login/$',
        LoginView.as_view(template_name='admin/login.html'), name='login'),
    url(r'^accounts/logout/$',
        LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^permission/', include('permission.urls')),
    url(r'^common/', include('common.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^dynamicpassword/$', DynamicPassword.as_view(), name='dynamicpassword'),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, }),
    ]

permission/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from common.models import ServerGroup
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission as AuthPermission
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _


class Permission(models.Model):
    user = models.OneToOneField(User, verbose_name=_(
        'User'), related_name='permissionuser')
    permissions = models.ManyToManyField(
        AuthPermission, verbose_name=_('Permissions'), related_name='permission')
    groups = models.ManyToManyField(
        ServerGroup, verbose_name=_('Server group'))
    createdatetime = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Create time'))
    updatedatetime = models.DateTimeField(
        auto_created=True, auto_now=True, verbose_name=_('Update time'))

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (
            ("can_add_user", _("Can add user")),
            ("can_change_user", _("Can change user info")),
            ("can_delete_user", _("Can delete user info")),
            ("can_view_user", _("Can view user info")),
            ("can_view_permissions", _("Can view user permissions")),
            ("can_change_permissions", _("Can change user permissions")),
            ("can_delete_permissions", _("Can revoke user permissions")),
            ("can_add_permissions", _("Can add user permissions")),
        )


class Role(models.Model):
    user = models.OneToOneField(User, verbose_name=_(
        'User'), related_name='roleuser')
    permissions = models.ManyToManyField(
        AuthPermission, verbose_name=_('Permissions'), related_name='rolepermission', limit_choices_to={'content_type__app_label__in': ['common', 'permission'], "codename__contains": 'can_'})
    groups = models.ManyToManyField(
        ServerGroup, verbose_name=_('Server group'))
    createdatetime = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Create time'))
    updatedatetime = models.DateTimeField(
        auto_created=True, auto_now=True, verbose_name=_('Update time'))

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (
            ("can_add_user", _("Can add role")),
            ("can_change_user", _("Can change role info")),
            ("can_delete_user", _("Can delete role info")),
            ("can_view_user", _("Can view role info")),
            ("can_view_permissions", _("Can view role permissions")),
            ("can_change_permissions", _("Can change role permissions")),
            ("can_delete_permissions", _("Can revoke role permissions")),
            ("can_add_permissions", _("Can add role permissions")),
        )

permission/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, render_to_response, HttpResponseRedirect
from django.views.generic import FormView, DetailView, DeleteView, ListView, UpdateView, CreateView
from django.contrib.auth.models import User
from permission.forms import RegisterForm, PermissionForm
from django.core.urlresolvers import reverse_lazy
from permission.models import Permission
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.mixins import PermissionRequiredMixin
from common.views import LoginRequiredMixin


class UserRegister(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    template_name = 'permission/userregister.html'
    form_class = RegisterForm
    success_url = reverse_lazy('userlist')
    permission_required = 'permission.can_add_user'
    raise_exception = True

    def form_valid(self, form):
        username = form.cleaned_data['user']
        password = form.cleaned_data['newpassword1']
        email = form.cleaned_data['email']
        User.objects.create_user(
            username=username, email=email, password=password, is_active=True, is_staff=True)
        return HttpResponseRedirect(self.get_success_url())


class UserList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'permission/userlist.html'
    model = User
    permission_required = 'permission.can_view_user'
    raise_exception = True


class UserDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'permission/userdelete.html'
    model = User
    success_url = reverse_lazy('userlist')
    permission_required = 'permission.can_delete_user'
    raise_exception = True


class UserUpdate(LoginRequiredMixin, PermissionRequiredMixin, FormView, UpdateView):
    template_name = 'permission/userupdate.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('userlist')
    permission_required = 'permission.can_change_user'
    raise_exception = True

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        data = self.get_object()
        initial = super(UserUpdate, self).get_initial()
        initial['user'] = data.username
        initial['email'] = data.email
        return initial

    def form_valid(self, form):
        username = form.cleaned_data['user']
        password = form.cleaned_data['newpassword1']
        email = form.cleaned_data['email']
        data = self.get_object()
        if len(password) != 0:
            data.set_password(password)
        data.email = email
        data.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form(self, form_class=None):
        form = super(UserUpdate, self).get_form(form_class)
        form.fields['user'].widget.attrs.update({'readonly': True})
        form.fields['newpassword1'].required = False
        form.fields['newpassword2'].required = False
        return form


class PermissionCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Permission
    form_class = PermissionForm
    success_url = reverse_lazy('permissionlist')
    template_name = 'permission/permissioncreate.html'
    permission_required = 'permission.can_add_permissions'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super(PermissionCreate, self).get_context_data(**kwargs)
        context['title'] = _('Create Permission')
        return context

    def form_valid(self, form):
        user = form.cleaned_data['user']
        permissionset = form.cleaned_data['permissions']
        user.user_permissions.clear()
        user.user_permissions.add(*permissionset)
        user.save()
        self.object = form.save()
        return super(PermissionCreate, self).form_valid(form)

    def get_form(self, form_class=None):
        form = super(PermissionCreate, self).get_form(form_class)
        form.fields['permissions'].widget.attrs.update(
            {'checked': 'checked'})
        return form


class PermissionList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Permission
    template_name = 'permission/permissionlist.html'
    permission_required = 'permission.can_view_permissions'
    raise_exception = True


class PermissionUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Permission
    form_class = PermissionForm
    success_url = reverse_lazy('permissionlist')
    template_name = 'permission/permissioncreate.html'
    permission_required = 'permission.can_change_permissions'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super(PermissionUpdate, self).get_context_data(**kwargs)
        context['title'] = _('Update Permission')
        return context

    def form_valid(self, form):
        user = form.cleaned_data['user']
        permissionset = form.cleaned_data['permissions']
        user.user_permissions.clear()
        user.user_permissions.add(*permissionset)
        user.save()
        self.object = form.save()
        return super(PermissionUpdate, self).form_valid(form)


class PermissionDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Permission
    success_url = reverse_lazy('permissionlist')
    template_name = 'permission/permissiondelete.html'
    permission_required = 'permission.can_delete_permissions'
    raise_exception = True

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        user = self.object.user
        permissionset = self.object.permissions.all()
        for permission in permissionset:
            user.user_permissions.remove(permission)
            user.save()
        self.object.delete()
        return HttpResponseRedirect(success_url)

permission/templates/permission/permissioncreate.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{{ title }}{% endblock %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'plugins/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/select2-bootstrap-theme/dist/select2-bootstrap.min.css' %}">
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissionlist' %}'">
                            {%trans 'Return Permission List' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>

                <form id="id-m-form" action="" method="post" class="form form-horizontal " role="form">
                    <div class="box-body">
                        {% if form.helper %}
                            {% crispy form form.helper %}
                        {% else %}
                            {% crispy form %}
                        {% endif %}
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-primary">{%trans 'submit' %}</button>
                                <button type="button" class="btn btn-default goback" onclick="history.back()">{%trans 'cancel' %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'plugins/select2/dist/js/select2.full.min.js' %}"></script>
<script type="application/javascript">
    $('#id_groups,#id_user').select2({
        theme: "bootstrap"
    });
</script>
<script>
  $("[href='{% url 'permissionlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}

permission/templates/permission/permissiondelete.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{%trans 'Permission delete' %}{% endblock %}
{% load staticfiles %}
{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissionlist' %}'">
                            {% trans 'Return Permission list' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">

                    <div class="row">


                        <div class="col-lg-10">
                            <div class="content float-e-margins">
                                <div class="content">
                                    <form action="" class="form-horizontal nice-validator n-yellow form" method="post" novalidate="novalidate">
                                        {% csrf_token %}
                                        <p>{%trans 'Are you sure you want to delete user permission' %} "{{ object.user.username }}"?</p>
                                        <div class="col-sm-4 col-sm-offset-5">
                                            <button type="submit" id="submit" class="btn btn-primary pull-center">
                                                {%trans 'submit' %}
                                            </button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script>
  $("[href='{% url 'permissionlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}

permission/templates/permission/permissionlist.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{%trans 'Permission list' %}{% endblock %}
{% load staticfiles %}
{% block css %}
<!-- DataTables css -->
<link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock %}
{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'permissioncreate' %}'">
                            {% trans 'Add New' %}
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">

                    <table id="permissionlist" class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>{%trans 'user name' %}</th>
                            <th>{%trans 'permissions' %}</th>
                            <th>{%trans 'groups' %}</th>
                            <th>{%trans 'action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for element in object_list %}
                        <tr>
                            <td>{{ element.user.username }}</td>
                            <td>
                                {% for permission in  element.permissions.all %}
                                    <a>{% trans permission.name %}</a><br>
                                {% endfor %}
                            </td>
                            <td>
                                {% for group in  element.groups.all %}
                                <a>{{group.name}}</a><br>
                                {% endfor %}
                            </td>
                            <td data-editable="false" class="text-center pull-left">
                                {% if perms.permission.can_change_permissions %}<a class="btn btn-xs btn-info" href="{% url 'permissionupdate' element.id %}">{%trans 'edit' %}</a>{% endif %}
                                {% if perms.permission.can_delete_permissions %}<a class="btn btn-xs btn-danger" href="{% url 'permissiondelete' element.id %}">{%trans 'delete' %}</a>{% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static "plugins/datatables/dataTables.bootstrap.min.js" %}"></script>
<script type="application/javascript">
    $(function () {
        $('#permissionlist').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "iDisplayLength": 50,
            "autoWidth": false,
        });
    });
</script>
{% endblock %}

permission/templates/permission/userdelete.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{%trans 'User delete' %}{% endblock %}
{% load staticfiles %}
{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'userlist' %}'">
                            {% trans 'Return user list' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">

                    <div class="row">


                        <div class="col-lg-10">
                            <div class="content float-e-margins">
                                <div class="content">
                                    <form action="" class="form-horizontal nice-validator n-yellow form" method="post" novalidate="novalidate">
                                        {% csrf_token %}
                                        <p>{%trans 'Are you sure you want to delete user' %} "{{ object }}"?</p>
                                        <div class="col-sm-4 col-sm-offset-5">
                                            <button type="submit" id="submit" class="btn btn-primary pull-center">
                                                {%trans 'submit' %}
                                            </button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script>
  $("[href='{% url 'userlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}

permission/templates/permission/userregister.html
{% extends 'base.html'%}
{%load i18n%}
{% block title %}{%trans 'Add new user' %}{% endblock %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="box box-success">
                <div class="box-header with-border">
                    <div class="caption">
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'userlist' %}'">
                            {%trans 'Return user List' %}
                        </button>
                    </div>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">{%trans 'Action' %}</a></li>
                                <li><a href="#">{%trans 'Another action' %}</a></li>
                                <li><a href="#">{%trans 'Something else here' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="#">{%trans 'Separated link' %}</a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>

                    <form id="id-m-form" action="" method="post" class="form form-horizontal " role="form">
                            <div class="box-body">
                                {% if form.helper %}
                                    {% crispy form form.helper %}
                                {% else %}
                                    {% crispy form %}
                                {% endif %}
                                <div class="form-group">
                                    <div class="col-xs-offset-2 col-xs-10">
                                        <button type="submit" class="btn btn-primary">{%trans 'submit' %}</button>
                                        <button type="button" class="btn btn-default goback" onclick="history.back()">{%trans 'cancel' %}</button>
                                    </div>
                                </div>
                            </div>
                    </form>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
</section>
{% endblock %}
{% block js %}
<script>
  $("[href='{% url 'userlist' %}']").parent("li").addClass('active')
</script>
{% endblock %}